language: ruby
rvm:
  - 1.9.3
  - 2.0.0
install:
  - mkdir -p ~/local/src
  - cd ~/local/src
  - wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
  - tar xvf vim-*.tar.bz2
  - cd vim74
  - ./configure --prefix=~/local
  - make && make install
script:
  - export PATH=~/local/bin:${PATH}
  - bundle install
  - bundle exec rake spec
