language: ruby
rvm:
  - 1.9.3
  - 2.0.0
install:
  - pushd
  - mkdir -p ~/local/src
  - cd ~/local/src
  - wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
  - tar xvf vim-*.tar.bz2
  - cd vim74
  - ./configure --prefix=${HOME}/local/vim74
  - make && make install
  - popd
script:
  - bundle install
  - export PATH=${HOME}/local/vim74/bin:${PATH}
  - bundle exec rake spec
